#ifndef FIELD_SIZES_H
#define FIELD_SIZES_H

#define DATA_START_BYTES 2
#define TOTAL_NUM_FILES_BYTES 2

#define FILENAME_LEN_BYTES 2
#define DATA_START_OFFSET_BYTES 4
#define FILE_SIZE_BYTES 2

#endif
